config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  
  resources :articles

  resources :accounts, only: [:show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:create]
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  scope module: :apps do
    resource :profile, only: [:show, :edit, :update]
    resource :timeline, only: [:show]
    resources :timelines, only: [:index]
  end

  namespace :api, defaults: {format: :json} do
    scope '/articles/:article_id' do
      resources :comments, only: [:create, :destroy, :index]
      resource :like, only: [:show, :create, :destroy]
    end
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :bigint           not null
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_article_id  (article_id)
#  index_comments_on_user_id     (user_id)
#
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :content, presence: true

  after_create :send_email

  private

  def send_email
    @Users = User.all
    @Users.each do |each_user|
      if content.include?("@#{each_user.name}")
        NoticeMailer.new_comment(user, content, each_user, article).deliver_later
      end
    end
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
 
  def index
    article = Article.find(params[:article_id])
    comments = article.comments

    render json: comments, each_serializer: CommentSerializer, include: { user: [:profile] }
  end
  
  # def new
  #   article = Article.find(params[:article_id])
  #   @comment = article.comments.build
  # end

  def create
    article = Article.find(params[:article_id])
    @comment = article.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!

    render json: @comment, each_serializer: CommentSerializer, include: { user: [:profile] }
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :avatar)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def index
    article = Article.find(params[:article_id])
    comments = article.comments

    render json: comments, each_serializer: CommentSerializer, include: { user: [:profile] }
  end
  
  def new
    article = Article.find(params[:article_id])
    @comment = article.comments.build
  end

  def create
    article = Article.find(params[:article_id])
    @comment = article.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!

    render json: @comment, each_serializer: CommentSerializer, include: { user: [:profile] }
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :avatar)
  end
end

app/views/comments/index.html.haml
-# .conteiner 
-#   .comment_header
-#     .comment_back_icon.left
-#       = link_to image_tag('back_arrow.png'), :back 
-#     .title.center
-#       %h2 Comment

-# .container 
-#   .card_detail
-#     = image_tag @article.user.avatar_image
-#     %div
-#       %h3= @article.author_name
-#       %p= post_time(@article.created_at)
-#       %p= @article.content

-# .container
-#   .comments_container
-#   - @comments.each do |comment|
-#     .comment_user_detail 
-#       = image_tag @article.user.avatar_image
-#       %div
-#         %h3= @article.author_name
-#         %p= post_time(comment.created_at)
-#         %p= comment.content

-# = javascript_pack_tag 'article'

app/views/comments/new.html.haml
-# .container 
-#   %ul 
-#     - @comment.errors.full_messages.each do |message|
-#       %li= message

-#   = form_with(model: @comment, url: article_comments_path(@comment.article), local: true) do |f|
-#     %div 
-#       = f.label :content, 'Content'
-#     %div
-#       = f.text_area :content
-#     = f.submit 'Save', class: 'btn-primary'