config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  
  resources :articles

  resources :accounts, only: [:show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:create]
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  scope module: :apps do
    resource :profile, only: [:show, :edit, :update]
    resource :timeline, only: [:show]
    resources :timelines, only: [:index]
  end

  namespace :api, defaults: {format: :json} do
    scope '/articles/:article_id' do
      resources :comments, only: [:create, :destroy, :index]
      resource :like, only: [:show, :create, :destroy]
    end
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  has_many_attached :images
  validates :content, presence: true, length: {minimum: 2}

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  def author_name
    user.display_name
  end

  def like_count
    likes.count
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Saved!'
    else
      flash.now[:error] = 'Save failed....'
      render :new
    end
  end

  # def edit
  #   @article = current_user.articles.find(params[:id])
  # end

  private
  def article_params
    params.require(:article).permit(:content, images: [])
  end
end

app/views/articles/index.html.haml
.container
  .title_header
    -# %nav.navbar.navbar-light.bg-light.d-flex
    .logo
      -# .camerabtn
      -#   = link_to new_article_path do 
      -#     %button
      -#       %i.fa-solid.fa-camera-retro
      .title
        %p Instagram
    .header_icon 
      .camerabtn
        = link_to new_article_path do 
          %button
            %i.fa-solid.fa-camera-retro
      .user-section
        - if user_signed_in?
          %a{"data-method" => "delete", :href => destroy_user_session_path}
            %i.fa.fa-user.fa-xl
        - else
          %a{:href => new_user_session_path}
            %i.fa-solid.fa-right-to-bracket.fa-xl
  - if flash.present?
    .flash
      - flash.each do |key, value|
        %div{:class => key}= value

  .cards_container
    - @articles.each do |article|    
      .card#article-show{data: {article_id: article.id}}
        .card_detail
          = image_tag article.user.avatar_image
          %div
            %h3= article.author_name
            %p= post_time(article.created_at)
        .card_grid
          - if article.images.attached?
            - article.images.each do |image|
              .card_image
                = image_tag image.variant(resize: '170!x100').processed, class: 'card_image_large'
        .card_content
          .card_icon
            - if user_signed_in?
              .card_icon_heart.hidden.active-heart{:id => "#{article.id}"}
                = image_tag 'heart-active.svg', class: 'active-heart'
              .card_icon_heart.hidden.inactive-heart{:id => "#{article.id}"}
                = image_tag 'heart.svg', class: 'inactive-heart'
              .card_icon_comment
                = link_to new_article_comment_path(article) do  
                  = image_tag 'message.png'
              .card_icon_share
                = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do 
                  = image_tag 'share.png'
        %p= "Maki and #{article.like_count} other liked your post"
        .card_caption
          %h3= article.author_name
        = link_to article_path(article) do
          %p= article.content

= javascript_pack_tag 'article' 

app/views/articles/new.html.haml
.container
  = form_with(model: @article, url: articles_path, method: 'post', local: true) do |f|
    .new_header
      .cancelbtn 
        = link_to 'Cance', root_path 
      %div
        %p.status_button Status
      #postBtn 
        %p Post

    .article_card
      .article_author 
        .article_author_image
          = image_tag @article.user.avatar_image, class: 'avatar-image'
        .article_author_name
          = @article.author_name
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message
        -# = form_with(model: @article, url: articles_path, method: 'post', local: true) do |f|
        %div
          = f.text_field :content, placeholder: "What's on your mind?", class: 'post_content_form'
        %div
          = f.label :images, '+ Album', class: 'images_input_btn' do
            %i.images_form_name + Album 
            = f.file_field :images, multiple: true, class: 'hidden'
        
        = f.submit '保存', class: 'hidden'

= javascript_pack_tag 'article'

app/views/articles/show.html.haml
.container#article-show{data: {article_id: @article.id}}
  .form_header  
    .return_page.left-element
      = link_to root_path do
        = image_tag 'back_arrow.png'
    .page_name.center-element
      %p Comments
  .card
    .card_detail
      = link_to account_path(@article.user) do
        = image_tag @article.user.avatar_image
      %div
        %h3= @article.author_name
        %p= post_time(@article.created_at)
    .card_grid
      - if @article.images.attached?
        - @article.images.each do |image|
          .card_image
            = image_tag image.variant(resize: '170!x100').processed, class: 'card_image_large'
    .card_content
      .card_icon
        - if user_signed_in?
          .card_icon_comment 
            = link_to article_path(@article) do
              = image_tag 'message.png'
          .card_icon_share
            = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do 
              = image_tag 'share.png'
      %p= "Maki and #{@article.like_count} other liked your post"
      .card_content_caption
        %h3= @article.author_name
        %p= @article.content
  .comments_container
  
  -# .comment-text-area
  -#   = text_area_tag :comment_content, '', class: 'sm'
  -#   .btn-secondary
  -#     = image_tag 'message.png', class: 'add-comment-button'

.comment_footer
  %nav.navbar.d-flex
    .comment-text-area
      = text_area_tag :comment_content, '', class: 'sm'
      .btn-secondary
        = image_tag 'message.png', class: 'add-comment-button'

      

= javascript_pack_tag 'article'