config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  
  resources :articles

  resources :accounts, only: [:show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:create]
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  scope module: :apps do
    resource :profile, only: [:show, :edit, :update]
    resource :timeline, only: [:show]
    resources :timelines, only: [:index]
  end

  namespace :api, defaults: {format: :json} do
    scope '/articles/:article_id' do
      resources :comments, only: [:create, :destroy, :index]
      resource :like, only: [:show, :create, :destroy]
    end
  end
end

app/views/commons/_articles.html.haml
.container
  .title_header
    -# - if user_signed_in?
    .dropdown
      %p.title.dropbtn Instagram⊿
      .dropdown-content
        = link_to 'All Articles', root_path 
        = link_to 'folloings', timeline_path
        = link_to 'Liked top-5', timelines_path
    -# - if user_signed_in?
    -# .logo
    -#   .title
    -#     %p Instagram
    -#     .dropdown 
    -#       = link_to 'All Articles', root_path 
    -#       = link_to 'folloings', timeline_path

    .header_icon 
      .camerabtn
        = link_to new_article_path do 
          %button
            %i.fa-solid.fa-camera-retro
      .user-section
        - if user_signed_in?
          %a{"data-method" => "delete", :href => destroy_user_session_path}
            %i.fa.fa-user.fa-xl
        - else
          %a{:href => new_user_session_path}
            %i.fa-solid.fa-right-to-bracket.fa-xl
  - if flash.present?
    .flash
      - flash.each do |key, value|
        %div{:class => key}= value

  .cards_container
    - articles.each do |article|    
      .card#article-show{data: {article_id: article.id}}
        .card_detail
          = image_tag article.user.avatar_image
          %div
            %h3= article.author_name
            %p= post_time(article.created_at)
        .card_grid
          - if article.images.attached?
            - article.images.each do |image|
              .card_image
                = image_tag image.variant(resize: '170!x100').processed, class: 'card_image_large'
        .card_content
          .card_icon
            - if user_signed_in?
              .card_icon_heart.hidden.active-heart{:id => "#{article.id}"}
                = image_tag 'heart-active.svg', class: 'active-heart'
              .card_icon_heart.hidden.inactive-heart{:id => "#{article.id}"}
                = image_tag 'heart.svg', class: 'inactive-heart'
              .card_icon_comment
                = link_to article_path(article) do  
                  = image_tag 'message.png'
              .card_icon_share
                = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do 
                  = image_tag 'share.png'
        %p= "Maki and #{article.like_count} other liked your post"
        .card_caption
          %h3= article.author_name
        = link_to article_path(article) do
          %p= article.content

= javascript_pack_tag 'article' 

app/views/commons/_profile.html.haml
.profilePage 
  .container
    .profile_top 
      .profile_return_page 
        = link_to root_path do
          = image_tag 'back_arrow.png'
      .user_displayName 
        = user.display_name 
      .actionButton
        - if user_signed_in?
          - if user == current_user 
            = link_to 'Edit', edit_profile_path 
          - else
            .actionButton.hidden.un_follow-button#account-show{data: {account_id: @user.id, current_user_id: current_user.id}} 
              %p Unfollow
              -# = link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'} 
            .actionButton.hidden.follow-button#account-show{data: {account_id: @user.id, current_user_id: current_user.id}} 
              %p Follow
            -# = link_to 'Follow', account_follows_path(user), data: {method: 'post'} 
          -# - if current_user&.has_followed?(user)
          -#   = link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'} 
          -# - else
          -#   = link_to 'Follow', account_follows_path(user), data: {method: 'post'} 
 
    .profilePage_image
      = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
        = f.label :avatar do
          = image_tag user.avatar_image, class: 'avatar-image'
        %div
          = f.file_field :avatar, class: 'hidden uploader' 
          = f.submit 'SUBMIT', class: 'hidden submit-btn'

    .profilePage_dataBox 
      .profilePage_dataBox_inner 
        %p 44
        %p Posts 
      .profilePage_dataBox_inner
        = link_to account_followers_path(user) do
          %p#follower_number{data: {follower_count: user.follower_count}} 
            - if user == current_user
              #{current_user.follower_count}
            - else
              #{@user.follower_count}
          %p Followers
      .profilePage_dataBox_inner 
        = link_to account_followings_path(user) do
          %p.following_number
            #{user.following_count}
          %p Followings
    
= javascript_pack_tag 'account'